### ISSUE TITLE
lua fails to parse with custom type definitions

### ISSUE THREAD

**Issue by walksanatora** [fstirlitz/luaparse#118]
hello I like to use type checking in lua
so in my init.lua file i have this function 
```lua
local function getTableKeys(table:table)
    local keyset = {}
    for k,v in pairs(table) do
        keyset[#keyset + 1] = k
    end
    return keyset
end
```
and luamin fails with the following error 
```
[5:33] <name> or '...' expected near ':'

Error: failed to minify. Make sure the Lua code is valid.
If you think this is a bug in luamin, please report it:
https://github.com/mathiasbynens/luamin/issues/new

Stack trace using luamin@1.0.4 and luaparse@0.2.1:

SyntaxError: [5:33] <name> or '...' expected near ':'
    at raise (/home/walksanator/.nvm/versions/node/v16.10.0/lib/node_modules/luamin/node_modules/luaparse/luaparse.js:460:15)
    at raiseUnexpectedToken (/home/walksanator/.nvm/versions/node/v16.10.0/lib/node_modules/luamin/node_modules/luaparse/luaparse.js:482:5)
    at parseFunctionDeclaration (/home/walksanator/.nvm/versions/node/v16.10.0/lib/node_modules/luamin/node_modules/luaparse/luaparse.js:1676:11)
    at parseLocalStatement (/home/walksanator/.nvm/versions/node/v16.10.0/lib/node_modules/luamin/node_modules/luaparse/luaparse.js:1565:14)
    at parseStatement (/home/walksanator/.nvm/versions/node/v16.10.0/lib/node_modules/luamin/node_modules/luaparse/luaparse.js:1291:41)
    at parseBlock (/home/walksanator/.nvm/versions/node/v16.10.0/lib/node_modules/luamin/node_modules/luaparse/luaparse.js:1271:19)
    at parseChunk (/home/walksanator/.nvm/versions/node/v16.10.0/lib/node_modules/luamin/node_modules/luaparse/luaparse.js:1248:16)
    at end (/home/walksanator/.nvm/versions/node/v16.10.0/lib/node_modules/luamin/node_modules/luaparse/luaparse.js:2094:17)
    at parse (/home/walksanator/.nvm/versions/node/v16.10.0/lib/node_modules/luamin/node_modules/luaparse/luaparse.js:2065:31)
    at minify (/home/walksanator/.nvm/versions/node/v16.10.0/lib/node_modules/luamin/luamin.js:621:6)
```

and also when trying to minify a file with type defs
[DataTypes.lua](https://github.com/mathiasbynens/luamin/files/7908993/DataTypes.lua.txt)
 it fails with the following
```
[5:0] unexpected identifier 'export' near 'Vec3T'

Error: failed to minify. Make sure the Lua code is valid.
If you think this is a bug in luamin, please report it:
https://github.com/mathiasbynens/luamin/issues/new

Stack trace using luamin@1.0.4 and luaparse@0.2.1:

SyntaxError: [5:0] unexpected identifier 'export' near 'Vec3T'
    at raise (/home/walksanator/.nvm/versions/node/v16.10.0/lib/node_modules/luamin/node_modules/luaparse/luaparse.js:460:15)
    at unexpected (/home/walksanator/.nvm/versions/node/v16.10.0/lib/node_modules/luamin/node_modules/luaparse/luaparse.js:512:14)
    at parseAssignmentOrCallStatement (/home/walksanator/.nvm/versions/node/v16.10.0/lib/node_modules/luamin/node_modules/luaparse/luaparse.js:1624:12)
    at parseStatement (/home/walksanator/.nvm/versions/node/v16.10.0/lib/node_modules/luamin/node_modules/luaparse/luaparse.js:1316:12)
    at parseBlock (/home/walksanator/.nvm/versions/node/v16.10.0/lib/node_modules/luamin/node_modules/luaparse/luaparse.js:1271:19)
    at parseChunk (/home/walksanator/.nvm/versions/node/v16.10.0/lib/node_modules/luamin/node_modules/luaparse/luaparse.js:1248:16)
    at end (/home/walksanator/.nvm/versions/node/v16.10.0/lib/node_modules/luamin/node_modules/luaparse/luaparse.js:2094:17)
    at parse (/home/walksanator/.nvm/versions/node/v16.10.0/lib/node_modules/luamin/node_modules/luaparse/luaparse.js:2065:31)
    at minify (/home/walksanator/.nvm/versions/node/v16.10.0/lib/node_modules/luamin/luamin.js:621:6)
    at /home/walksanator/.nvm/versions/node/v16.10.0/lib/node_modules/luamin/bin/luamin:69:14
```
(copied from [https://github.com/mathiasbynens/luamin/issues/84](https://github.com/mathiasbynens/luamin/issues/84))

**Comment by fstirlitz** [comment]
Lua has no type annotations.
